# src/AppBundle/Resources/config/routing.yml

app_home:
    path:     /
    defaults: 
     _controller: AppBundle:Geo:index

app_add_sample:
    path:     /add/sample
    defaults: 
     _controller: AppBundle:Geo:addsample
     
app_add_document:
    path:     /add/document
    defaults: 
     _controller: AppBundle:Geo:adddocument
     
app_add_points:
    path:     /add/points
    defaults: 
     _controller: AppBundle:Geo:addpoints
     
app_add_outcrop:
    path:     /add/outcrop
    defaults: 
     _controller: AppBundle:Geo:addoutcrop
     
app_add_drilling:
    path:     /add/drilling
    defaults: 
     _controller: AppBundle:Geo:adddrilling
     
app_search_sample:
    path:     /search/sample
    defaults: 
     _controller: AppBundle:Geo:searchsample
     
app_result_sample:
    path:     /results/sample/{queryvals}  
    defaults: 
     _controller: AppBundle:Geo:results_searchsample
     queryvals: ""
     
app_collection_list:
    path:     /get_collections/{querygroup}  
    defaults: 
     _controller: AppBundle:Geo:listcodecollection
    methods:  GET
    
app_minerals_list:
    path:     /get_minerals/{querygroup}  
    defaults: 
     _controller: AppBundle:Geo:listminerals
    methods:  GET
    
app_lithominerals_list:
    path:     /get_lithominerals
    defaults: 
     _controller: AppBundle:Geo:listlithominerals
    methods:  GET
    
app_code_autocomplete:
    path:     /get_code/
    defaults: 
     _controller: AppBundle:Geo:Code_autocomplete
    methods:  GET
     
app_search_document:
    path:     /search/document
    defaults: 
     _controller: AppBundle:Geo:searchdocument
     
app_search_points:
    path:     /search/points
    defaults: 
     _controller: AppBundle:Geo:searchpoints
     
app_search_outcrop:
    path:     /search/outcrop
    defaults: 
     _controller: AppBundle:Geo:searchoutcrop
     
app_search_drilling:
    path:     /search/drilling
    defaults: 
     _controller: AppBundle:Geo:searchdrilling
     
app_admin:
    path:     /admin
    defaults: 
     _controller: AppBundle:Geo:admin
     
app_login:
    path:     /login
    defaults: 
     _controller: AppBundle:Security:login